Mappb list added
jmfrancklab/pyspecdata pull request #55
Opened 2024-08-28 19:28 UTC by wfkincaid

2024-08-28 19:29 UTC, wfkincaid commented
need to add descriptions to docstring

2024-08-29 16:21 UTC, jmfranck requested changes

2024-08-29 16:21 UTC, jmfranck commented on pyspecdata/plot_funcs/pcolormesh.py
> +    mappable_list: list of
please fill out -- see example [here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html)

2024-08-29 20:02 UTC, jmfranck commented on pyspecdata/plot_funcs/pcolormesh.py
> +    ax2 : matplotlib axes object
please note that my format for numpy docstrings wasn't quite to spec, so I'm fixing it moving forward (that's what I'm doing here)

2024-08-29 20:03 UTC, jmfranck commented on pyspecdata/plot_funcs/pcolormesh.py
> +        axis. Used to make all 3x2 plots under a uniform color scale
again, fixing it to be to spec (see also [here](https://github.com/numpy/numpydoc/issues/284)).

note also that I'm doing `gq` to wrap the text to a reasonable width.

2024-08-29 20:03 UTC, merged