Dcct lines
jmfrancklab/pyspecdata pull request #65
Opened 2024-11-04 22:33 UTC by guinneak198

use blended scale transformation so the lines under the coherence transfer labels scale with window like the arrows do

2024-11-04 23:29 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +        ax1_to_figure = ax1.transAxes + fig.transFigure.inverted()
I don't understand why you need this. I see where it is implemented, but I do not understand why any spacing, etc. that you need to specify between the plots and what not can't be specified using figure coordinates.

Phrased differently, I don't see any need for any coordinate systems aside from the following:

- The blended transform where the Y values are just figure coordinates, and the X values are in display units, with the to the bottom left corner of the bottom left figure. (Achieved with a scaled translation.)
    - this coordinate system is used to specify all of the decoration on the left-hand side aside from the arrows on the bottom
- a coordinate system where all values are in display units with the origin set to the bottom left corner of the bottom left figure. This is achieved using scaledtranslation, and is the coordinate system that is used for the X coordinates of the previous coordinate system. So, this coordinate system should actually be defined first, and then input into the blended transform factory.
   - as clarified in the Slack conversation, this is used for the arrows

2024-11-04 23:42 UTC, jmfranck requested changes

2024-11-04 23:42 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +    )
So line 208 to hear is what I am describing in my long comment. These are the only two coordinate systems that you should need.

2024-11-04 23:43 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +    dx = LHS_labels + LHS_pad  # Fig coord
This somehow got moved. It applies to line 206 below.

2024-11-04 23:44 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +        ax1_to_figure = ax1.transAxes + fig.transFigure.inverted()
This applies to the definition of all these extra coordinate systems like `ax1_to_figure`, etc

2024-11-04 23:45 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +        ax1_to_figure = ax1.transAxes + fig.transFigure.inverted()
[see here](https://github.com/jmfrancklab/pyspecdata/pull/65#discussion_r1828541716)

2024-11-04 23:48 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +            r_[0 - allow_for_ticks - label_spacing, 0.95]
This is an explicit evaluation of the transform which we are trying to avoid

2024-11-04 23:50 UTC, jmfranck commented
Also, the arrows are in the wrong place. The tip of the arrow should be immediately underneath the vertical lines.  Or if you disagree with that the middle of the text.  

The right most arrow is good, but the others are far to the left of the thing that they are pointing to

2024-11-04 23:51 UTC, jmfranck commented
Because the X coordinate for both of your new coordinate systems is the same it should actually be very easy now to line up the arrows with whatever you are trying to line them up with along the X coordinate

2024-11-05 16:25 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +    dx = LHS_labels + LHS_pad  # Fig coord
This is to get the coord (if fig coord) of the bottom left point of the bottom axes

2024-11-05 17:00 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +    dx = LHS_labels + LHS_pad  # Fig coord
see line 187 (LHS_labels is in display coords)

2024-11-05 19:09 UTC, jmfranck commented
see [here](https://chatgpt.com/share/672a6d43-3900-800b-a84b-555cf2d299d6) on adding an image to the documentation.

2024-11-11 19:45 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> -    text_height=40,
no longer used

2024-11-11 19:46 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +    # }}}
I didn't change the transform of the arrows but moved it up here for better reading with the other transforms

2024-11-11 19:48 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +    label_placed = np.zeros(num_dims)
This was above randomly between the 2 function definitions so I moved it here for organization

2024-11-14 14:17 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +            ax_list[j].yaxis.set_major_locator(plt.MaxNLocator(integer=True))
unsure what is going on here but needed for flake to pass

2024-11-14 14:20 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +            r_[0, 0.05]
taking y coordinates directly from axes objects since this is more straightforward than guessing the coordinates in figure coords

2024-11-14 14:20 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        x_axorigindisp, y_axorigindisp = ax1.transAxes.transform(r_[0, 0])
flake said this is used elsewhere so I took out of if loop

2025-01-04 14:25 UTC, guinneak198 commented on examples/DCCT_function.py
> +    fig = fl.next("Data")  # Make figure object to place the DCCT
separated these so that comments can explicitly explian the use of each

2025-01-09 20:08 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +
There are several places where we go from axes to figure coords specifically it's used to get the coordinate of the bottom left corner of the bottom axes. It is much easier to use this as a pinpoint of reference since the coord in axes coords is 0,0

2025-01-09 20:09 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        dx, ax_y0, fig.transFigure
renamed the y to be more descriptive that we are using the y coord for ax[0]

2025-01-09 20:11 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        _, y2_fig = ax_to_fig(ax2, fig).transform(r_[0, 0.05])
this is where I use the function that I defined above going from axes coords (easy, (0,0) or(0,1)) to figure coords for the final scaled translation

2025-01-09 20:33 UTC, jmfranck commented on examples/DCCT_function.py
> +    plt.plot(
also, I don't see that this example demonstrates that goal, which you showed [here](https://jmfrancklab.slack.com/files/UKMUSV589/F0809A7P60H/desired_dcct_kwargs.pdf)

2025-01-09 20:35 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> -    grid_bottom += bottom_pad
also, you refer to the "grid" and I don't understand what the "grid" is.  Maybe it's in the docstring and I missed it?

2025-01-09 20:35 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +        y-coordinate top of grid in figure
again, aren't these given by the bbox??

2025-01-10 17:37 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
this would allow stacked DCCTs so we can adjust the top of the DCCT

2025-01-10 18:10 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
But the bounding box already allows you to stack them.  Again, I would refer to [this](https://jmfrancklab.slack.com/messages/CK0FA3KL1/files/F0809A7P60H) which nicely shows that no such quantity is required!

2025-01-10 18:11 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +        y-coordinate top of grid in figure
to be clear, that's a rhetorical question

2025-01-10 18:21 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
ah assuming they are plotted in a subplot

2025-01-10 18:25 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
![image](https://github.com/user-attachments/assets/e2357032-11a8-405e-8eec-b445834862c9)
I can change top_pad to a variable rather than kwarg but there's gotta be some give for the title of the plot

2025-01-10 18:26 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
but the bounding box should control the position of the DCCT plot -- full stop

2025-01-10 18:27 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
[desired_DCCT_kwargs.pdf](https://github.com/user-attachments/files/18380887/desired_DCCT_kwargs.pdf)
This shows **all** the variables/kwargs that we need -- that's the point.

2025-01-10 18:31 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> -    grid_bottom += bottom_pad
this totally was an unneeded kwarg

2025-01-10 18:34 UTC, jmfranck commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
if you have a lot, or just for convenience, it looks like you could auto-determine the bbox values with GridSpec, like so (according to ChatGPT):
```
# Create a figure
fig = plt.figure()

# Define a 2x2 GridSpec
gs = gridspec.GridSpec(2, 2)

# Access the bounding box of a specific grid cell
row, col = 1, 0
bbox = gs[row, col].get_position(fig)

# Extract [left, bottom, width, height] as a list
bbox_list = list(bbox.bounds)
```

2025-01-10 19:38 UTC, guinneak198 commented on examples/DCCT_function.py
> +    plt.plot(
fixed so now DCCT_function shows just the one DCCT with the applicable kwargs (we had discussed and changed from the original you link but bbox is still relevant gap and label_spacer became more succinct as shown by the example

2025-01-12 21:43 UTC, jmfranck commented on examples/DCCT_function.py
> +    plt.plot(
so, the figure looks good, now, but it's not taking this comment into account.

2025-01-12 21:45 UTC, jmfranck commented on examples/DCCT_function.py
> +    plt.plot(
the point of this comment is that the numbers passed to plot below should also be passed to DCCT, so that someone can see where things are coming from.

For example, `bbox` should be passed to DCCT, and then `bbox[0]` should be used to determine the position of the relevant line.

2025-01-13 16:39 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
please note bbox[3] is no longer relevant we already have a nice way to format the spacing and height of the full figure based on the phase cycling dimension to determine how many axes are needed but will play with gridspec to try to implement what you are saying

2025-01-13 16:40 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
this addressed the to do in the example sccript as well

2025-01-13 17:10 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
This could be something neat for a future PR however the main objective here for this PR was to feed the function the bbox as a list. I've addressed the top pad already with bbox[3] which as you mentioned I had left out.

2025-01-13 19:08 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
ignore previous comment we discussed this is for plotting multiple dccts and using the gridspec position as the bbox arguments which I am good with and working on now!

2025-01-13 20:42 UTC, guinneak198 commented on examples/DCCT_function.py
> +    plt.plot(
checkmark

2025-01-13 20:43 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        Distance between top of figure and top of grid
see example DCCT_side_by_side.py where I do this

2025-01-15 22:13 UTC, jmfranck commented
before merging, we should change the inspection method inside ipy.py to use DCCT rather than image.

2025-01-15 23:36 UTC, jmfranck requested changes
see TODOs in my push

2025-01-16 22:21 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +                # position will increment with the number of the dimension
this addresses to do asking what x_textdisp is/how it's defined

2025-01-16 22:22 UTC, guinneak198 commented on pyspecdata/DCCT_function.py
> +        ax.sharey(ax_list[1])
to do said sharex and sharey first. These are not arguments for the axes in the axes list as we are making them one by one so when we say share x it doesn't understand this was AGs solution

2025-01-17 23:22 UTC, merged